 default[:seconion][:sensor][:bro][:extract][:mimetypes]["application/x-dosexec"] = "exe"
 default[:seconion][:sensor][:bro][:extract][:mimetypes]["application/x-java-applet"] = "class"
 default[:seconion][:sensor][:bro][:extract][:mimetypes]["application/x-java-archive"] = "jar"
 default[:seconion][:sensor][:bro][:extract][:mimetypes]["application/zip"] = "zip"
 default[:seconion][:sensor][:bro][:extract][:mimetypes]["application/pdf"] = "pdf"
 default[:seconion][:sensor][:bro][:extract][:mimetypes]["application/x-rar"] = "rar"
 default[:seconion][:sensor][:bro][:extract][:mimetypes]["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] = "docx"
 default[:seconion][:sensor][:bro][:extract][:mimetypes]["text/rtf"] = "rtf" 
